Opensrp
onaio/docker-builds pull request #9
Opened 2016-10-31 13:45 UTC by keymane

- OpenSRP docker files

2016-10-31 14:52 UTC, ukanga commented
@keymane can you remove the .DS_Store file, also add it to the `.gitignore` file.

2016-10-31 15:01 UTC, ukanga requested changes

2016-10-31 15:01 UTC, ukanga commented on opensrp/composed/.env
> +#!/bin/sh
I don't this file is supposed to be committed.

2016-10-31 15:01 UTC, ukanga commented on opensrp/composed/sh/start.sh
> +mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h mysql -e "CREATE DATABASE $MYSQL_MOTECH_DATABASE /*\!40100 DEFAULT CHARACTER SET utf8 */;"
`-h mysql` could you use a variable for the mysql host as well aka `$MYSQL_HOST`, you could set the variable at the start of the script.

2016-11-01 08:27 UTC, keymane commented
@ukanga I've made the changes requested

2016-11-02 14:21 UTC, ukanga approved these changes

2016-11-02 14:22 UTC, merged